Petstagram/photos/urls.py
from django.urls import path, include
from Petstagram.photos import views


urlpatterns = [
    path('add/', views.add_photo_page, name='add-photo'),
    path('<int:pk>/', include([
        path('', views.show_photo_details, name='photo-details'),
        path('edit/', views.photo_edit_page, name='edit-photo')
    ])),
]

Petstagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Petstagram.common.urls')),
    path('accounts/', include('Petstagram.accounts.urls')),
    path('pets/', include('Petstagram.pets.urls')),
    path('photos/', include('Petstagram.photos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Petstagram/photos/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from Petstagram.pets.models import Pet
from Petstagram.photos.validators import FileSizeValidator


# Create your models here.

class Photo(models.Model):
    photo = models.ImageField(
        upload_to='',
        validators=[
        FileSizeValidator(5)
    ])
    description = models.TextField(
        max_length=300,
        validators=[MinLengthValidator(10)],
        null=True,
        blank=True
    )
    location = models.CharField(max_length=30, null=True, blank=True)
    tagged_pets = models.ManyToManyField(Pet, blank=True)
    date_of_publication = models.DateField(auto_now=True)

Petstagram/photos/forms.py
from django import forms
from Petstagram.photos.models import Photo


class PhotoBaseForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = '__all__'


class PhotoAddForm(PhotoBaseForm):
    pass


class PhotoEditForm(PhotoBaseForm):
    pass


class PhotoDeleteForm(PhotoBaseForm):
    pass

Petstagram/photos/views.py
from django.shortcuts import render, redirect
from Petstagram.photos.models import Photo
from Petstagram.photos import forms


# Create your views here.

def add_photo_page(request):
    form = forms.PhotoAddForm(request.POST or None, request.FILES or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('home')

    context = {
        'form': form
    }

    return render(request, 'photos/photo-add-page.html', context)


def show_photo_details(request, pk):
    photo = Photo.objects.get(pk=pk)
    photo_likes = photo.like_set.all()
    comments = photo.comments.all()

    context = {
        'photo': photo,
        'photo_likes': photo_likes,
        'comments': comments,  # Change this to 'comments' instead of 'photo_comments'
    }

    return render(request, 'photos/photo-details-page.html', context)


def photo_edit_page(request, pk):
    return render(request, 'photos/photo-edit-page.html')

templates/photos/photo-add-page.html
{% extends 'common/base.html' %}

{% block content %}
	


<main>
    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <form action="" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="add-btn">Submit</button>
        </form>
    </div>
</main>
{% endblock %}

templates/photos/photo-details-page.html
{% extends 'common/base.html' %}

{% block content %}
    <div class="container">
        <div class="col-9">
            {% include 'common/pet-posts.html' with photo_page=True %}
        </div>
    </div>
{% endblock %}

templates/photos/photo-edit-page.html
{% extends 'common/base.html' %}

{% block content %}
	

<main>

    <!-- Starts Edit Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <!-- Starts Edit Photo Form -->
        <form action="">

            <p>
                <label for="id_description">Description:</label>
                <input type="text" value="Sasho is an Axolotl">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"
                       value="Bansko, Bulgaria">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option selected>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>

            <!-- Edit Photo Button -->
            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>
        <!-- End Edit Photo Form -->

    </div>
    <!-- End Edit Photo Section -->

</main>
{% endblock %}